name: Ansi
version: '${version}'

main: de.lifemytouch.ansi.Ansi
api-version: '1.21'
load: POSTWORLD

commands:
  gm:
    aliases: [gamemode]
    description: Verwaltet den Gamemode eines Spielers
  rang:
    aliases: [rank]
    description: Verwaltet den Rang eines Spielers
  report:
    description: Meldet einen Spieler
  reports:
    description: Öffnet die Report-Liste
  fly:
    aliases: [flight]
    description: Erlaubt dem Spieler das Fliegen
  vanish:
    aliases: [v]
    description: Versteckt den Spieler vor anderen
  ban:
    description: Bannt einen Spieler
  mute:
    description: Muted einen Spieler
  kick:
    description: Kickt einen Spieler
  history:
    description: Zeigt die Punish History eines Spielers
  unpunish:
    aliases: [unban, unmute]
    description: Hebt die Sperre eines Spielers auf
  lobby:
    aliases: [spawn, l, hub]
    description: Teleportiert dich zum Spawn der Lobby
  build:
    description: Erlaubt dem Spieler das Bauen
  friend:
    description: Freunde
  coins:
    description: Verwaltet die Coins eines Spielers
  uuid:
    description: Hohlt die UUID von einem Spieler
  teleport:
    aliases: [tp]
    description: Teleportiert dich zu einem Spieler
  staffchat:
    aliases: [sc]
    description: Aktiviert oder deaktiviert den Staff-Chat
  stafflist:
    aliases: [staff]
    description: Zeigt die online Teammitglieder
  msg:
    aliases: [message, tell, w]
    description: Sendet einem Spieler eine private Nachricht
  playtime:
    aliases: [pt]
    description: Zeigt die Spielzeit eines Spielers
  maintenance:
    aliases: [maint]
    description: Verwaltet den Wartungsmodus
  anticheat:
    aliases: [ac]
    description: Verwaltet das AntiCheat